### PR TITLE
Add configuration of OAUTH/Telegram notifications via Docker environment variables

### PR DESCRIPTION
**Pull request by dr460nf1r3**
## Summary

Adds further variables to configure the Docker container with. Especially for settings which are secrets, this comes in very handy as it allows using .env files for secrets.

### Checklist

- [ ] Tests to cover new code
- [ ] `make check` passed
- [ ] `make tests` passed

### CODE REVIEW

**Comment by arcan1s** [comment]
the main reason why it wasn't implemented before is that there are multiple possible configurations and several different triggers. Like you mr includes only telegram and oauth tokens, however, there are also `web.password` option, s3 settings (in some cases rsync/remote pull and push triggers can also expose secrets) (~ [list of secrets](https://github.com/arcan1s/ahriman/blob/master/src/ahriman/core/formatters/configuration_printer.py#L34)). 

After all it comes with configuration in which user would like to use (for example) multiple telegram channels with different settings in each, which is clearly impossible withing these changes.

Instead of this, I think it might be achieved if we would allow to set options in configuration via system environment, e.g. passing file like:

```
[web]
password = %(VERY_SECURE_ENV_VAR)s
```

would read `VERY_SECURE_ENV_VAR` variable and assign it into `web.password` (there is no need actually to predefine such vars in `Dockerfile`)

In addition `sudo` call should be replaced with `sudo -E`.

What do you think, will this feature cover your case?

**Comment by arcan1s** [comment]
Preview of mentioned above feature has been added in https://github.com/arcan1s/ahriman/commit/572880eb73bdad87645436e2f02c86d16da14296, based on documentation example, you can pass variable AHRIMAN_OAUTH_CLIENT_ID and the following config:

```
...
client_id = $AHRIMAN_OAUTH_CLIENT_ID
...
```

In this example `AHRIMAN_OAUTH_CLIENT_ID` will be automatically read from environment

**Comment by dr460nf1r3** [comment]
Sounds like a very good idea to handle this particular case! :)

**Comment by arcan1s** [comment]
does it work for you or would you still like to have some adjustments in dockerfile? (I mean can this mr be closed or not :smile: ) anyway, thank you for your contribution!

**Comment by dr460nf1r3** [comment]
That absolutely works! I didn't get to test it yet due to being busy working, but that's even better than a customized Dockerfile. Great work 😁

**Comment by dr460nf1r3** [comment]
Got to test the commit - works perfectly fine!

**Pull request closed without merging**
